# Generated by Django 3.2.16 on 2022-12-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploads',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileF# Generated by Django 3.2.16 on 2022-12-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploads',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
